import { LearnPageLocale, LearnTarget } from './targets';

/**
 * The language name in the form required by “learn X” in that interface language.
 * English and German names are capitalized. Others stay lowercase, except scripts
 * that have no case and Turkish, where the name can open the sentence.
 */
export const learnLanguageNames: Record<LearnPageLocale, Record<LearnTarget, string>> = {
  en: {
    en: 'English',
    es: 'Spanish',
    zh: 'Chinese',
    fr: 'French',
    de: 'German',
    ja: 'Japanese',
    ko: 'Korean',
    ar: 'Arabic',
    pt: 'Portuguese',
    it: 'Italian',
    pl: 'Polish',
    ru: 'Russian',
    id: 'Indonesian',
    ms: 'Malay',
    th: 'Thai',
    tr: 'Turkish',
    vi: 'Vietnamese',
    sr: 'Serbian',
  },
  ru: {
    en: 'английский',
    es: 'испанский',
    zh: 'китайский',
    fr: 'французский',
    de: 'немецкий',
    ja: 'японский',
    ko: 'корейский',
    ar: 'арабский',
    pt: 'португальский',
    it: 'итальянский',
    pl: 'польский',
    ru: 'русский',
    id: 'индонезийский',
    ms: 'малайский',
    th: 'тайский',
    tr: 'турецкий',
    vi: 'вьетнамский',
    sr: 'сербский',
  },
  uk: {
    en: 'англійську',
    es: 'іспанську',
    zh: 'китайську',
    fr: 'французьку',
    de: 'німецьку',
    ja: 'японську',
    ko: 'корейську',
    ar: 'арабську',
    pt: 'португальську',
    it: 'італійську',
    pl: 'польську',
    ru: 'російську',
    id: 'індонезійську',
    ms: 'малайську',
    th: 'тайську',
    tr: 'турецьку',
    vi: 'в’єтнамську',
    sr: 'сербську',
  },
  be: {
    en: 'англійскую',
    es: 'іспанскую',
    zh: 'кітайскую',
    fr: 'французскую',
    de: 'нямецкую',
    ja: 'японскую',
    ko: 'карэйскую',
    ar: 'арабскую',
    pt: 'партугальскую',
    it: 'італьянскую',
    pl: 'польскую',
    ru: 'рускую',
    id: 'інданезійскую',
    ms: 'малайскую',
    th: 'тайскую',
    tr: 'турэцкую',
    vi: 'в’етнамскую',
    sr: 'сербскую',
  },
  pl: {
    en: 'angielskiego',
    es: 'hiszpańskiego',
    zh: 'chińskiego',
    fr: 'francuskiego',
    de: 'niemieckiego',
    ja: 'japońskiego',
    ko: 'koreańskiego',
    ar: 'arabskiego',
    pt: 'portugalskiego',
    it: 'włoskiego',
    pl: 'polskiego',
    ru: 'rosyjskiego',
    id: 'indonezyjskiego',
    ms: 'malajskiego',
    th: 'tajskiego',
    tr: 'tureckiego',
    vi: 'wietnamskiego',
    sr: 'serbskiego',
  },
  de: {
    en: 'Englisch',
    es: 'Spanisch',
    zh: 'Chinesisch',
    fr: 'Französisch',
    de: 'Deutsch',
    ja: 'Japanisch',
    ko: 'Koreanisch',
    ar: 'Arabisch',
    pt: 'Portugiesisch',
    it: 'Italienisch',
    pl: 'Polnisch',
    ru: 'Russisch',
    id: 'Indonesisch',
    ms: 'Malaiisch',
    th: 'Thailändisch',
    tr: 'Türkisch',
    vi: 'Vietnamesisch',
    sr: 'Serbisch',
  },
  fr: {
    en: "l'anglais",
    es: "l'espagnol",
    zh: 'le chinois',
    fr: 'le français',
    de: "l'allemand",
    ja: 'le japonais',
    ko: 'le coréen',
    ar: "l'arabe",
    pt: 'le portugais',
    it: "l'italien",
    pl: 'le polonais',
    ru: 'le russe',
    id: "l'indonésien",
    ms: 'le malais',
    th: 'le thaï',
    tr: 'le turc',
    vi: 'le vietnamien',
    sr: 'le serbe',
  },
  es: {
    en: 'inglés',
    es: 'español',
    zh: 'chino',
    fr: 'francés',
    de: 'alemán',
    ja: 'japonés',
    ko: 'coreano',
    ar: 'árabe',
    pt: 'portugués',
    it: 'italiano',
    pl: 'polaco',
    ru: 'ruso',
    id: 'indonesio',
    ms: 'malayo',
    th: 'tailandés',
    tr: 'turco',
    vi: 'vietnamita',
    sr: 'serbio',
  },
  it: {
    en: "l'inglese",
    es: 'lo spagnolo',
    zh: 'il cinese',
    fr: 'il francese',
    de: 'il tedesco',
    ja: 'il giapponese',
    ko: 'il coreano',
    ar: "l'arabo",
    pt: 'il portoghese',
    it: "l'italiano",
    pl: 'il polacco',
    ru: 'il russo',
    id: "l'indonesiano",
    ms: 'il malese',
    th: 'il tailandese',
    tr: 'il turco',
    vi: 'il vietnamita',
    sr: 'il serbo',
  },
  pt: {
    en: 'inglês',
    es: 'espanhol',
    zh: 'chinês',
    fr: 'francês',
    de: 'alemão',
    ja: 'japonês',
    ko: 'coreano',
    ar: 'árabe',
    pt: 'português',
    it: 'italiano',
    pl: 'polonês',
    ru: 'russo',
    id: 'indonésio',
    ms: 'malaio',
    th: 'tailandês',
    tr: 'turco',
    vi: 'vietnamita',
    sr: 'sérvio',
  },
  sv: {
    en: 'engelska',
    es: 'spanska',
    zh: 'kinesiska',
    fr: 'franska',
    de: 'tyska',
    ja: 'japanska',
    ko: 'koreanska',
    ar: 'arabiska',
    pt: 'portugisiska',
    it: 'italienska',
    pl: 'polska',
    ru: 'ryska',
    id: 'indonesiska',
    ms: 'malajiska',
    th: 'thailändska',
    tr: 'turkiska',
    vi: 'vietnamesiska',
    sr: 'serbiska',
  },
  da: {
    en: 'engelsk',
    es: 'spansk',
    zh: 'kinesisk',
    fr: 'fransk',
    de: 'tysk',
    ja: 'japansk',
    ko: 'koreansk',
    ar: 'arabisk',
    pt: 'portugisisk',
    it: 'italiensk',
    pl: 'polsk',
    ru: 'russisk',
    id: 'indonesisk',
    ms: 'malajisk',
    th: 'thailandsk',
    tr: 'tyrkisk',
    vi: 'vietnamesisk',
    sr: 'serbisk',
  },
  no: {
    en: 'engelsk',
    es: 'spansk',
    zh: 'kinesisk',
    fr: 'fransk',
    de: 'tysk',
    ja: 'japansk',
    ko: 'koreansk',
    ar: 'arabisk',
    pt: 'portugisisk',
    it: 'italiensk',
    pl: 'polsk',
    ru: 'russisk',
    id: 'indonesisk',
    ms: 'malayisk',
    th: 'thailandsk',
    tr: 'tyrkisk',
    vi: 'vietnamesisk',
    sr: 'serbisk',
  },
  id: {
    en: 'bahasa Inggris',
    es: 'bahasa Spanyol',
    zh: 'bahasa Mandarin',
    fr: 'bahasa Prancis',
    de: 'bahasa Jerman',
    ja: 'bahasa Jepang',
    ko: 'bahasa Korea',
    ar: 'bahasa Arab',
    pt: 'bahasa Portugis',
    it: 'bahasa Italia',
    pl: 'bahasa Polandia',
    ru: 'bahasa Rusia',
    id: 'bahasa Indonesia',
    ms: 'bahasa Melayu',
    th: 'bahasa Thailand',
    tr: 'bahasa Turki',
    vi: 'bahasa Vietnam',
    sr: 'bahasa Serbia',
  },
  ms: {
    en: 'bahasa Inggeris',
    es: 'bahasa Sepanyol',
    zh: 'bahasa Mandarin',
    fr: 'bahasa Perancis',
    de: 'bahasa Jerman',
    ja: 'bahasa Jepun',
    ko: 'bahasa Korea',
    ar: 'bahasa Arab',
    pt: 'bahasa Portugis',
    it: 'bahasa Itali',
    pl: 'bahasa Poland',
    ru: 'bahasa Rusia',
    id: 'bahasa Indonesia',
    ms: 'bahasa Melayu',
    th: 'bahasa Thai',
    tr: 'bahasa Turki',
    vi: 'bahasa Vietnam',
    sr: 'bahasa Serbia',
  },
  tr: {
    en: 'İngilizce',
    es: 'İspanyolca',
    zh: 'Çince',
    fr: 'Fransızca',
    de: 'Almanca',
    ja: 'Japonca',
    ko: 'Korece',
    ar: 'Arapça',
    pt: 'Portekizce',
    it: 'İtalyanca',
    pl: 'Lehçe',
    ru: 'Rusça',
    id: 'Endonezce',
    ms: 'Malayca',
    th: 'Tayca',
    tr: 'Türkçe',
    vi: 'Vietnamca',
    sr: 'Sırpça',
  },
  vi: {
    en: 'tiếng Anh',
    es: 'tiếng Tây Ban Nha',
    zh: 'tiếng Trung',
    fr: 'tiếng Pháp',
    de: 'tiếng Đức',
    ja: 'tiếng Nhật',
    ko: 'tiếng Hàn',
    ar: 'tiếng Ả Rập',
    pt: 'tiếng Bồ Đào Nha',
    it: 'tiếng Ý',
    pl: 'tiếng Ba Lan',
    ru: 'tiếng Nga',
    id: 'tiếng Indonesia',
    ms: 'tiếng Mã Lai',
    th: 'tiếng Thái',
    tr: 'tiếng Thổ Nhĩ Kỳ',
    vi: 'tiếng Việt',
    sr: 'tiếng Serbia',
  },
  th: {
    en: 'ภาษาอังกฤษ',
    es: 'ภาษาสเปน',
    zh: 'ภาษาจีน',
    fr: 'ภาษาฝรั่งเศส',
    de: 'ภาษาเยอรมัน',
    ja: 'ภาษาญี่ปุ่น',
    ko: 'ภาษาเกาหลี',
    ar: 'ภาษาอาหรับ',
    pt: 'ภาษาโปรตุเกส',
    it: 'ภาษาอิตาลี',
    pl: 'ภาษาโปแลนด์',
    ru: 'ภาษารัสเซีย',
    id: 'ภาษาอินโดนีเซีย',
    ms: 'ภาษามาเลย์',
    th: 'ภาษาไทย',
    tr: 'ภาษาตุรกี',
    vi: 'ภาษาเวียดนาม',
    sr: 'ภาษาเซอร์เบีย',
  },
  ar: {
    en: 'الإنجليزية',
    es: 'الإسبانية',
    zh: 'الصينية',
    fr: 'الفرنسية',
    de: 'الألمانية',
    ja: 'اليابانية',
    ko: 'الكورية',
    ar: 'العربية',
    pt: 'البرتغالية',
    it: 'الإيطالية',
    pl: 'البولندية',
    ru: 'الروسية',
    id: 'الإندونيسية',
    ms: 'الملايوية',
    th: 'التايلاندية',
    tr: 'التركية',
    vi: 'الفيتنامية',
    sr: 'الصربية',
  },
  ja: {
    en: '英語',
    es: 'スペイン語',
    zh: '中国語',
    fr: 'フランス語',
    de: 'ドイツ語',
    ja: '日本語',
    ko: '韓国語',
    ar: 'アラビア語',
    pt: 'ポルトガル語',
    it: 'イタリア語',
    pl: 'ポーランド語',
    ru: 'ロシア語',
    id: 'インドネシア語',
    ms: 'マレー語',
    th: 'タイ語',
    tr: 'トルコ語',
    vi: 'ベトナム語',
    sr: 'セルビア語',
  },
  ko: {
    en: '영어',
    es: '스페인어',
    zh: '중국어',
    fr: '프랑스어',
    de: '독일어',
    ja: '일본어',
    ko: '한국어',
    ar: '아랍어',
    pt: '포르투갈어',
    it: '이탈리아어',
    pl: '폴란드어',
    ru: '러시아어',
    id: '인도네시아어',
    ms: '말레이어',
    th: '태국어',
    tr: '터키어',
    vi: '베트남어',
    sr: '세르비아어',
  },
  zh: {
    en: '英语',
    es: '西班牙语',
    zh: '中文',
    fr: '法语',
    de: '德语',
    ja: '日语',
    ko: '韩语',
    ar: '阿拉伯语',
    pt: '葡萄牙语',
    it: '意大利语',
    pl: '波兰语',
    ru: '俄语',
    id: '印尼语',
    ms: '马来语',
    th: '泰语',
    tr: '土耳其语',
    vi: '越南语',
    sr: '塞尔维亚语',
  },
  sr: {
    en: 'енглески',
    es: 'шпански',
    zh: 'кинески',
    fr: 'француски',
    de: 'немачки',
    ja: 'јапански',
    ko: 'корејски',
    ar: 'арапски',
    pt: 'португалски',
    it: 'италијански',
    pl: 'пољски',
    ru: 'руски',
    id: 'индонежански',
    ms: 'малајски',
    th: 'тајски',
    tr: 'турски',
    vi: 'вијетнамски',
    sr: 'српски',
  },
};
