export interface Topic {
  task: string;
  level: "easy" | "medium" | "hard";
}

export const topicsToDiscuss: Topic[] = [
  {
    task: "If you could live in any country for a year, where would you go and why?",
    level: "medium",
  },
  {
    task: "Describe a perfect weekend — no limits on time or money.",
    level: "easy",
  },
  {
    task: "What’s one invention you wish existed?",
    level: "medium",
  },
  {
    task: "Do you believe animals can understand human emotions?",
    level: "medium",
  },
  {
    task: "Is it better to be book-smart or street-smart?",
    level: "hard",
  },
  {
    task: "Would you rather travel to the past or the future? What would you do there?",
    level: "medium",
  },
  {
    task: "Talk about a movie or book that changed the way you think.",
    level: "medium",
  },
  {
    task: "Do social media platforms help or hurt real communication?",
    level: "hard",
  },
  {
    task: "Imagine you can talk to your 10-year-old self. What advice would you give?",
    level: "easy",
  },
  {
    task: "If you had to give a speech to the world for 2 minutes, what would you say?",
    level: "hard",
  },
  {
    task: "Describe your daily morning routine.",
    level: "easy",
  },
  {
    task: "Talk about a time you helped someone.",
    level: "medium",
  },
  {
    task: "Is technology making people less social?",
    level: "hard",
  },
  {
    task: "What is your favorite movie?",
    level: "easy",
  },
  {
    task: "What is your favorite food and why?",
    level: "easy",
  },
  {
    task: "Talk about your best friend.",
    level: "easy",
  },
  {
    task: "Should governments control what people see online?",
    level: "hard",
  },
  {
    task: "Talk about your best friend.",
    level: "easy",
  },
  {
    task: "What is one goal you want to achieve this year?",
    level: "medium",
  },
  {
    task: "Describe a memorable trip you've taken.",
    level: "medium",
  },
  {
    task: "What is the best gift you’ve ever received?",
    level: "medium",
  },
  {
    task: "Is it better to work for passion or money?",
    level: "hard",
  },
  {
    task: "Should governments control what people see online?",
    level: "hard",
  },
  {
    task: "What is your favorite food and why?",
    level: "easy",
  },
  {
    task: "What role does art play in society?",
    level: "hard",
  },
  {
    task: "What is your favorite movie?",
    level: "easy",
  },
  {
    task: "Is it better to work for passion or money?",
    level: "hard",
  },
  {
    task: "What is your favorite season?",
    level: "easy",
  },
  {
    task: "Talk about a time you helped someone.",
    level: "medium",
  },
  {
    task: "Do you prefer cities or nature? Why?",
    level: "medium",
  },
  {
    task: "What does success mean to you?",
    level: "medium",
  },
  {
    task: "What is your favorite season?",
    level: "easy",
  },
  {
    task: "What are the pros and cons of globalization?",
    level: "hard",
  },
  {
    task: "What is your favorite season?",
    level: "easy",
  },
  {
    task: "Describe your dream job.",
    level: "medium",
  },
  {
    task: "Describe your hometown.",
    level: "easy",
  },
  {
    task: "What is one goal you want to achieve this year?",
    level: "medium",
  },
  {
    task: "What is your favorite season?",
    level: "easy",
  },
  {
    task: "What is your favorite animal and why?",
    level: "easy",
  },
  {
    task: "What is one goal you want to achieve this year?",
    level: "medium",
  },
  {
    task: "What is your favorite season?",
    level: "easy",
  },
  {
    task: "How do you define happiness?",
    level: "hard",
  },
  {
    task: "Should governments control what people see online?",
    level: "hard",
  },
  {
    task: "Should animals be used for scientific testing?",
    level: "hard",
  },
  {
    task: "What is one goal you want to achieve this year?",
    level: "medium",
  },
  {
    task: "Describe your dream job.",
    level: "medium",
  },
  {
    task: "What do you like to do in your free time?",
    level: "easy",
  },
  {
    task: "What would you do if you won the lottery?",
    level: "medium",
  },
  {
    task: "What is the best gift you’ve ever received?",
    level: "medium",
  },
  {
    task: "Do you prefer cities or nature? Why?",
    level: "medium",
  },
  {
    task: "Is technology making people less social?",
    level: "hard",
  },
  {
    task: "How do you define happiness?",
    level: "hard",
  },
  {
    task: "Should governments control what people see online?",
    level: "hard",
  },
  {
    task: "What does success mean to you?",
    level: "medium",
  },
  {
    task: "Talk about your favorite holiday.",
    level: "easy",
  },
  {
    task: "What is one goal you want to achieve this year?",
    level: "medium",
  },
  {
    task: "Describe a memorable trip you've taken.",
    level: "medium",
  },
  {
    task: "What is your favorite animal and why?",
    level: "easy",
  },
  {
    task: "Talk about your favorite holiday.",
    level: "easy",
  },
  {
    task: "Describe a memorable trip you've taken.",
    level: "medium",
  },
  {
    task: "What role does art play in society?",
    level: "hard",
  },
  {
    task: "Talk about your best friend.",
    level: "easy",
  },
  {
    task: "Can money buy happiness?",
    level: "hard",
  },
  {
    task: "What would you do if you won the lottery?",
    level: "medium",
  },
  {
    task: "Talk about a time you helped someone.",
    level: "medium",
  },
  {
    task: "Is technology making people less social?",
    level: "hard",
  },
  {
    task: "What do you usually do on weekends?",
    level: "easy",
  },
  {
    task: "What do you think makes a good friend?",
    level: "medium",
  },
  {
    task: "What would you do if you won the lottery?",
    level: "medium",
  },
  {
    task: "What is the best gift you’ve ever received?",
    level: "medium",
  },
  {
    task: "What do you think makes a good friend?",
    level: "medium",
  },
  {
    task: "Describe your daily morning routine.",
    level: "easy",
  },
  {
    task: "Should governments control what people see online?",
    level: "hard",
  },
  {
    task: "Do you prefer cities or nature? Why?",
    level: "medium",
  },
  {
    task: "Talk about a hobby you'd like to start.",
    level: "medium",
  },
  {
    task: "Do you think schools prepare students for real life?",
    level: "hard",
  },
  {
    task: "What do you like to do in your free time?",
    level: "easy",
  },
  {
    task: "Talk about your favorite holiday.",
    level: "easy",
  },
  {
    task: "What is the best gift you’ve ever received?",
    level: "medium",
  },
  {
    task: "What is your favorite movie?",
    level: "easy",
  },
  {
    task: "Should governments control what people see online?",
    level: "hard",
  },
  {
    task: "Talk about your favorite holiday.",
    level: "easy",
  },
  {
    task: "Should governments control what people see online?",
    level: "hard",
  },
  {
    task: "Is it better to work for passion or money?",
    level: "hard",
  },
  {
    task: "Describe your dream job.",
    level: "medium",
  },
  {
    task: "What would you do if you won the lottery?",
    level: "medium",
  },
  {
    task: "How do you define happiness?",
    level: "hard",
  },
  {
    task: "What do you think makes a good friend?",
    level: "medium",
  },
  {
    task: "Describe your dream job.",
    level: "medium",
  },
  {
    task: "Talk about your favorite holiday.",
    level: "easy",
  },
  {
    task: "Talk about your best friend.",
    level: "easy",
  },
  {
    task: "Describe a memorable trip you've taken.",
    level: "medium",
  },
  {
    task: "What do you usually do on weekends?",
    level: "easy",
  },
  {
    task: "Describe your hometown.",
    level: "easy",
  },
  {
    task: "What is your favorite food and why?",
    level: "easy",
  },
  {
    task: "What does success mean to you?",
    level: "medium",
  },
  {
    task: "How do you define happiness?",
    level: "hard",
  },
  {
    task: "What is your favorite animal and why?",
    level: "easy",
  },
  {
    task: "What is your favorite animal and why?",
    level: "easy",
  },
  {
    task: "Do you prefer cities or nature? Why?",
    level: "medium",
  },
  {
    task: "Describe your hometown.",
    level: "easy",
  },
  {
    task: "What do you usually do on weekends?",
    level: "easy",
  },
  {
    task: "Do you prefer cities or nature? Why?",
    level: "medium",
  },
  {
    task: "Do you think schools prepare students for real life?",
    level: "hard",
  },
  {
    task: "Talk about a time you helped someone.",
    level: "medium",
  },
  {
    task: "What do you think makes a good friend?",
    level: "medium",
  },
  {
    task: "What is your favorite season?",
    level: "easy",
  },
  {
    task: "Talk about a hobby you'd like to start.",
    level: "medium",
  },
  {
    task: "Describe your dream job.",
    level: "medium",
  },
  {
    task: "What is your favorite food and why?",
    level: "easy",
  },
  { task: "Should people have to pass a test to become parents?", level: "hard" },
  { task: "Is cancel culture a form of justice or mob mentality?", level: "hard" },
  { task: "Should governments ban private cars in city centers?", level: "medium" },
  { task: "Is monogamy outdated?", level: "hard" },
  { task: "Should voting be mandatory in democracies?", level: "medium" },
  { task: "Can cheating ever be justified?", level: "hard" },
  { task: "Is free speech more important than protecting feelings?", level: "hard" },
  { task: "Should schools teach religion or ban it entirely?", level: "medium" },
  { task: "Are humans naturally selfish or good?", level: "medium" },
  { task: "Should euthanasia be legal?", level: "hard" },
  { task: "Is patriotism dangerous?", level: "hard" },
  { task: "Should rich people be taxed more heavily?", level: "medium" },
  { task: "Is it ethical to eat meat in the modern world?", level: "hard" },
  { task: "Should AI have rights?", level: "hard" },
  { task: "Is love just a chemical reaction?", level: "medium" },
  { task: "Should influencers be held to the same standards as journalists?", level: "medium" },
  { task: "Is prison effective, or just revenge?", level: "hard" },
  { task: "Should beauty standards be banned in advertising?", level: "medium" },
  { task: "Can fame ruin a person?", level: "easy" },
  { task: "Is lying always wrong?", level: "medium" },
  { task: "Should voting age be lowered to 16?", level: "medium" },
  { task: "Is poverty a choice?", level: "hard" },
  { task: "Should we forgive public figures who commit crimes?", level: "hard" },
  { task: "Are some cultures better than others?", level: "hard" },
  { task: "Is it wrong to be rich in a poor world?", level: "hard" },
  { task: "Should students be allowed to grade their teachers?", level: "easy" },
  { task: "Can violence ever be moral?", level: "hard" },
  { task: "Should drugs be legalized?", level: "hard" },
  { task: "Is democracy the best form of government?", level: "medium" },
  { task: "Should people have to work to receive government aid?", level: "medium" },
  { task: "Should prisoners be allowed to vote?", level: "medium" },
  { task: "Is social media destroying real-life relationships?", level: "medium" },
  { task: "Should people be paid for donating organs?", level: "hard" },
  { task: "Is religion more harmful than helpful in modern society?", level: "hard" },
  { task: "Should billionaires even exist?", level: "hard" },
  { task: "Is nationalism just a socially accepted prejudice?", level: "hard" },
  { task: "Should men and women compete together in sports?", level: "hard" },
  { task: "Does money corrupt people?", level: "medium" },
  { task: "Should we give robots power over life-and-death decisions?", level: "hard" },
  { task: "Is true equality possible?", level: "hard" },
  { task: "Should parents be punished for their children's crimes?", level: "medium" },
  { task: "Are trigger warnings making people emotionally weaker?", level: "medium" },
  { task: "Is it ethical to have children during a climate crisis?", level: "hard" },
  { task: "Should celebrities be role models?", level: "easy" },
  { task: "Are traditional gender roles still relevant?", level: "medium" },
  { task: "Can patriotism coexist with globalism?", level: "hard" },
  { task: "Should companies be punished for polluting, even if it hurts jobs?", level: "medium" },
  { task: "Is love a choice or a feeling?", level: "medium" },
  { task: "Should hate speech be protected as free speech?", level: "hard" },
  { task: "Can war ever be truly justified?", level: "hard" },
  { task: "Is spying on citizens ever acceptable for security?", level: "hard" },
  { task: "Should education be completely free?", level: "medium" },
  { task: "Should genetic engineering on humans be allowed?", level: "hard" },
  { task: "Is marriage still relevant today?", level: "medium" },
  { task: "Do beauty pageants do more harm than good?", level: "medium" },
  { task: "Can someone be both a patriot and a rebel?", level: "medium" },
  { task: "Is ambition more important than kindness?", level: "medium" },
  { task: "Should all drugs be decriminalized?", level: "hard" },
  { task: "Is capitalism failing society?", level: "hard" },
  { task: "Can people truly change?", level: "medium" },
  { task: "Should the internet be censored?", level: "hard" },
  { task: "Is death penalty ever acceptable?", level: "hard" },
  { task: "Should school uniforms be mandatory?", level: "easy" },
  { task: "Do men and women think differently?", level: "medium" },
  { task: "Is privacy dead in the digital age?", level: "hard" },
  { task: "Should rich countries help poor countries?", level: "medium" },
  { task: "Can a society exist without laws?", level: "hard" },
  { task: "Is freedom of speech being abused?", level: "hard" },
  { task: "Should cloning be banned?", level: "hard" },
  { task: "Is the idea of ‘the American Dream’ still alive?", level: "medium" },
  { task: "Should people be allowed to sell their own data?", level: "hard" },
  { task: "Is it okay to separate art from the artist?", level: "medium" },
  { task: "Should schools ban grades?", level: "medium" },
  { task: "Is space exploration a waste of money?", level: "medium" },
  { task: "Should unpaid internships be illegal?", level: "medium" },
  { task: "Are we becoming too dependent on technology?", level: "medium" },
  { task: "Is it ethical to manipulate genetics to avoid disabilities?", level: "hard" },
  { task: "Should prostitution be legalized and regulated?", level: "hard" },
  { task: "Is surveillance in public spaces a violation of privacy?", level: "hard" },
  { task: "Should the drinking age be lowered?", level: "medium" },
  { task: "Can ignorance be an excuse?", level: "medium" },
  { task: "Should violent video games be banned for minors?", level: "medium" },
  { task: "Is nationalism just modern tribalism?", level: "hard" },
  { task: "Should humans colonize other planets?", level: "medium" },
  { task: "Can artificial intelligence be truly creative?", level: "hard" },
  { task: "Should people be forced to recycle?", level: "medium" },
  { task: "Is the customer always right?", level: "easy" },
  { task: "Should school be year-round?", level: "medium" },
  { task: "Are grades an accurate measure of intelligence?", level: "medium" },
  { task: "Is gender a social construct?", level: "hard" },
  { task: "Should we have a universal basic income?", level: "hard" },
  { task: "Can machines replace human teachers?", level: "hard" },
  { task: "Should parents be able to choose their baby’s traits?", level: "hard" },
  { task: "Is violence in media harming society?", level: "medium" },
  { task: "Should governments regulate diets to fight obesity?", level: "medium" },
  { task: "Should history classes include more controversial topics?", level: "medium" },
  { task: "Are we too focused on individual rights?", level: "hard" },
  { task: "Is fame a form of addiction?", level: "medium" },
  { task: "Should voting be done online?", level: "medium" },
  { task: "Is morality subjective or universal?", level: "hard" },
  { task: "Should people be punished for offensive jokes?", level: "hard" },
  { task: "Is traditional marriage outdated?", level: "medium" },
  { task: "Can racism ever fully disappear?", level: "hard" },
  { task: "Should healthcare be a basic human right?", level: "medium" },
  { task: "Is society too obsessed with productivity?", level: "medium" },
  { task: "Should college be free for everyone?", level: "medium" },
  { task: "Is patriotism used to manipulate people?", level: "hard" },
  { task: "Can humans live without religion?", level: "hard" },
  { task: "Is the world becoming less free?", level: "hard" },
  { task: "Should we forgive historical figures for their views?", level: "medium" },
  { task: "Should people be fired for things they post online?", level: "hard" },
  { task: "Is the education system broken?", level: "medium" },
  { task: "Should hate groups be allowed to exist legally?", level: "hard" },
  { task: "Are conspiracy theories always dangerous?", level: "medium" },
  { task: "Is monogamy a social construct?", level: "hard" },
  { task: "Should all prisons be abolished?", level: "hard" },
  { task: "Is it okay to use personal tragedy for fame?", level: "medium" },
  { task: "Should all countries open their borders?", level: "hard" },
  { task: "Are reparations for historical injustices fair?", level: "hard" },
  { task: "Is it ethical to have children in an overpopulated world?", level: "hard" },
  { task: "Should teachers carry guns in schools?", level: "hard" },
  { task: "Is political correctness hurting free speech?", level: "hard" },
  { task: "Can social media be considered a public utility?", level: "medium" },
  { task: "Should influencers have legal responsibilities?", level: "medium" },
  { task: "Is it moral to buy products made in sweatshops?", level: "hard" },
  { task: "Are protest movements effective?", level: "medium" },
  { task: "Should governments censor fake news?", level: "hard" },
  { task: "Should voting rights be earned rather than given?", level: "hard" },
  { task: "Is capitalism inherently unfair?", level: "hard" },
  { task: "Are men and women truly treated equally today?", level: "medium" },
  { task: "Should people lose citizenship for serious crimes?", level: "hard" },
  { task: "Can revolutions be peaceful and successful?", level: "medium" },
  { task: "Is mental health treated seriously enough?", level: "medium" },
  { task: "Should rich kids have fewer opportunities in school admissions?", level: "hard" },
  { task: "Should animal testing be banned completely?", level: "medium" },
  { task: "Is addiction a choice or a disease?", level: "medium" },
  { task: "Should minimum wage be a living wage?", level: "medium" },
  { task: "Are online mobs a form of modern justice?", level: "hard" },
  { task: "Should artists be ‘canceled’ for past actions?", level: "medium" },
  { task: "Is immigration a threat or a benefit?", level: "hard" },
  { task: "Should public transport be free?", level: "medium" },
  { task: "Is overpopulation a myth?", level: "hard" },
  { task: "Should we limit the number of children per family?", level: "hard" },
  { task: "Are loyalty to nation and loyalty to humanity in conflict?", level: "hard" },
  { task: "Should taxes be voluntary?", level: "hard" },
  { task: "Can terrorism ever be understood?", level: "hard" },
  { task: "Should we let failing companies die?", level: "medium" },
  { task: "Is the concept of beauty harmful?", level: "medium" },
  { task: "Is there such a thing as objective truth?", level: "hard" },
  { task: "Should religion be banned from politics?", level: "hard" },
];
