packages:
  - .

allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - valibot@1.2.0
  - '@tootallnate/once@3.0.1'
  - yaml@2.8.3
  - next@16.2.3
  - postcss@8.5.10
trustPolicy: no-downgrade
